## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: Ayu Dark
# Scheme author: Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)

"text"     = {fg = "#e6e1cf", bg = "#0b0e14"}
"dimmed"   = {fg = "#3e4b59", bg = "#0b0e14"}
"title"    = {fg = "#59c2ff", bold = true}
"shortcut" = {fg = "#d2a6ff"}
"matched"  = {fg = "#e6b673"}
"border"   = {fg = "#3e4b59"}
"selected" = {bg = "#131721", fg = "#e6e1cf", bold = true}

"source_marker" = {bg = "#39bae6", fg = "#0b0e14", bold = true}
"target_marker" = {bg = "#7fd962", fg = "#0b0e14", bold = true}

"status"       = {bg = "#131721"}
"status title" = {fg = "#0b0e14", bg = "#73b8ff", bold = true}

"revset title"               = {fg = "#59c2ff", bold = true}
"revset text"                = {fg = "#e6e1cf", bold = true}
"revset completion text"     = {fg = "#e6e1cf"}
"revset completion matched"  = {fg = "#e6b673", bold = true}
"revset completion dimmed"   = {fg = "#3e4b59"}
"revset completion selected" = {bg = "#202229", fg = "#e6e1cf"}

"revisions"                  = {fg = "#e6e1cf"}
"revisions selected"         = {bg = "#131721"}
"revisions dimmed"           = {fg = "#3e4b59"}
"revisions details selected" = {bg = "#202229"}
"oplog selected"             = {bold = true}

"evolog"          = {fg = "#e6e1cf"}
"evolog selected" = {bg = "#202229", fg = "#e6e1cf", bold = true}

"menu"          = {bg = "#0b0e14"}
"menu title"    = {fg = "#0b0e14", bg = "#ddbcff", bold = true}
"menu shortcut" = {fg = "#ddbcff"}
"menu matched"  = {fg = "#e6b673", bold = true}
"menu dimmed"   = {fg = "#3e4b59"}
"menu border"   = {fg = "#131721"}
"menu selected" = {bg = "#202229", fg = "#e6e1cf"}

"help"        = {bg = "#0b0e14"}
"help title"  = {fg = "#7fd962", bold = true, underline = true}
"help border" = {fg = "#131721"}

"preview"        = {fg = "#e6e1cf"}
"preview border" = {fg = "#131721"}

"confirmation"          = {bg = "#0b0e14"}
"confirmation text"     = {fg = "#59c2ff", bold = true}
"confirmation dimmed"   = {fg = "#3e4b59"}
"confirmation border"   = {fg = "#f26d78", bold = true}
"confirmation selected" = {bg = "#202229", fg = "#e6e1cf"}

"undo"                       = {bg = "#0b0e14"}
"undo confirmation dimmed"   = {fg = "#3e4b59"}
"undo confirmation selected" = {bg = "#202229", fg = "#e6e1cf"}

"success"                        = {fg = "#7fd962", bold = true}
"error"                          = {fg = "#f26d78", bold = true}
"revisions rebase source_marker" = {bold = true}
"revisions rebase target_marker" = {bold = true}
"status shortcut"                = {fg = "#ddbcff"}
"status dimmed"                  = {fg = "#3e4b59"}

"details"             = {fg = "#e6e1cf"}
"details selected"    = {bold = true}
"completion"          = {fg = "#e6e1cf"}
"completion selected" = {bold = true}
"rebase"              = {bold = true}

"workspace" = {fg = "#73b8ff"}
"branch"    = {fg = "#39bae6"}
"commit"    = {fg = "#7fd962"}
"file"      = {fg = "#e6b673"}
"change"    = {fg = "#f26d78"}
"bookmark"  = {fg = "#ddbcff"}
